### ISSUE TITLE
Store connections

### ISSUE THREAD

**Issue by thiagola92** [rohinivsenthil/rabbitrace#3]
Store connections after closing VSCode

![image](https://user-images.githubusercontent.com/9352894/170889365-114a1ee5-1834-4462-a6d0-93535c68f562.png)

**Comment by rohinivsenthil** [comment]
Currently the connections are tied to a workspace. Can you give more details on when the issue occurs?

**Comment by thiagola92** [comment]
Sorry, i have multiple projects and was expecting to open the same connection on each one
